- name: Install supervisor
  tags: supervisor
  apt: name=supervisor state=present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Make sure supervisor is running and started on boot
  tags: supervisor
  service: name=supervisor state=started enabled=yes
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Make sure supervisor job is configured
  tags: supervisor
  template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/{{ item.key }}-worker.conf
  with_dict: "{{ virtualhosts }}"
  when: item.value.run_queue_worker|default(false)|bool == true and ansible_distribution == 'Ubuntu'
  vars:
    user: www-data
  notify:
    - Reload supervisord config (Debian)

- name: Make sure supervisor job is configured for Horizon
  tags: supervisor
  template: src=supervisor-horizon.conf.j2 dest=/etc/supervisor/conf.d/{{ item.key }}-horizon.conf
  with_dict: "{{ virtualhosts }}"
  when: item.value.run_horizon|default(false)|bool == true and ansible_distribution == 'Ubuntu'
  vars:
    user: www-data
  notify:
    - Reload supervisord config (Debian)