- name: Install certbot
  tags: letsencrypt
  apt: name=certbot state=present

- name: Check if Diffie-Hellman group exists
  tags: letsencrypt2
  stat:
    path: /etc/ssl/certs/dhparam.pem
  register: group_exists

- name: Generate a strong 2048 bit Diffie-Hellman group
  tags: letsencrypt2
  shell: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
  when: group_exists.stat.exists == false

- name: Install / renew certificates
  tags: letsencrypt
  command: >-
     certbot --nginx {% for host in item.value.servernames %}  -d {{ host }} {% endfor %}
     -m {{ letsencrypt_email }}
     --agree-tos --noninteractive --redirect
     --post-hook "/bin/true"
  register: certbot_output
  changed_when: "'Running post-hook command' in certbot_output.stdout"
  with_dict: "{{ virtualhosts }}"
  notify:
    - Restart nginx

- name: Add auto renewal for certificates to crontab
  tags: letsencrypt
  cron:
    name: "Weekly check for certificates"
    special_time: weekly
    job: /usr/bin/certbot renew --post-hook "service nginx restart"